const Permissions = {
    Perms: [
        "AddReactions",
        "Administrator",
        "AttachFiles",
        "BanMembers",
        "ChangeNickname",
        "Connect",
        "CreateInstantInvite",
        "CreatePrivateThreads",
        "CreatePublicThreads",
        "DeafenMembers",
        "EmbedLinks",
        "KickMembers",
        "ManageChannels",
        "ManageEmojisAndStickers",
        "ManageEvents",
        "ManageGuild",
        "ManageMessages",
        "ManageNicknames",
        "ManageRoles",
        "ManageThreads",
        "ManageWebhooks",
        "MentionEveryone",
        "ModerateMembers",
        "MoveMembers",
        "MuteMembers",
        "PrioritySpeaker",
        "ReadMessageHistory",
        "RequestToSpeak",
        "SendMessages",
        "SendMessagesInThreads",
        "SendTTSMessages",
        "Speak",
        "Stream",
        "UseApplicationCommands",
        "UseEmbeddedActivities",
        "UseExternalEmojis",
        "UseExternalStickers",
        "UseVAD",
        "ViewAuditLog",
        "ViewChannel",
        "ViewGuildInsights"
    ]
}

module.exports = Permissions